<!DOCTYPE html>
<html lang="en-US">
<!--********************************************-->
<!--*       Generated from PreTeXt source      *-->
<!--*       on 2022-08-10T16:19:19-04:00       *-->
<!--*   A recent stable commit (2020-08-09):   *-->
<!--* 98f21740783f166a773df4dc83cab5293ab63a4a *-->
<!--*                                          *-->
<!--*         https://pretextbook.org          *-->
<!--*                                          *-->
<!--********************************************-->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="robots" content="noindex, nofollow">
</head>
<body class="ignore-math">
<h3 class="heading"><span class="type">Paragraph</span></h3>
<p>It is also possible for a programmer to use nested try and except statements, along with different thrown errors to manage what happens in their code. The program will continue running after the error is caught, but we can stop this by returning a value other than 0 in our main function. This is known as an <code class="code-inline tex2jax_ignore">error code</code>.</p>
<span class="incontext"><a href="exception_-handling_exception-handling.html#p-578" class="internal">in-context</a></span>
</body>
</html>
